# Generated by Django 4.2 on 2023-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
