# Generated by Django 4.2 on 2023-05-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('duedate', models.DateField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.todolist')),
            ],
        ),
    ]
