# Generated by Django 4.2 on 2023-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(default='2023-05-06'),
        ),
    ]
